current-context: working-context
apiVersion: v1
clusters:
    - cluster:
          server: $KUBERNETES_SERVER
          insecure-skip-tls-verify: $INSECURE
      name: working-cluster
contexts:
    - context:
          cluster: working-cluster
          namespace: $NAMESPACE
          user: working-user
      name: working-context
kind: Config
preferences:
    colors: true
users:
    - name: working-user
      user:
          token: $EDIT_USER_TOKEN
