kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: github-actions-runner
  labels:
    build: github-actions-runner
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'github-actions-runner:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'docker.io/debian:buster-slim'
      pullSecret:
        name: docker-vestedbenes
      env:
        - name: http_proxy
          value: 'http://egress-http-proxy:8080'
        - name: https_proxy
          value: 'http://egress-http-proxy:8080'
        - name: HTTP_PROXY
          value: 'http://egress-http-proxy:8080'
        - name: HTTPS_PROXY
          value: 'http://egress-http-proxy:8080'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/axa-ch-cloud/github-runner.git'
  triggers:
    - type: GitHub
      github:
        secret: A6vwSStQJ_sbyk-mVFXb
    - type: Generic
      generic:
        secret: KNuEL60WeS6FcmgXpboV
    - type: ConfigChange
  runPolicy: Serial
