apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 5
  strategy:
    activeDeadlineSeconds: 21600
    resources:
      {{- toYaml .Values.resources.deployment | nindent 6 }}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: github-runner
      annotations:
        dynatrace.com/inject: 'false'
    spec:
      containers:
      - env:
        - name: SOPS_AGE_KEY_FILE
          value: /home/github/config/keys.txt
        - name: RUNNER_LABELS
          value: axa-trap-runner
        - name: GITHUB_OWNER
          value: axa-ch-cloud
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: trap-github-token
              key: token
        - name: HELM_KUBECAFILE
          value: /cacert/cacerts
        - name: HELM_KUBEAPISERVER
          value: 'https://kubernetes.default.svc:443'
        - name: no_proxy
          value: kubernetes.default.svc,api.red.switzerlandnorth.azure.openpaas.axa-cloud.com
        - name: HTTP_PROXY
          valueFrom:
            secretKeyRef:
              name: swissproxy
              key: proxy_url
        - name: HTTPS_PROXY
          valueFrom:
            secretKeyRef:
              name: swissproxy
              key: proxy_url
        - name: http_proxy
          valueFrom:
            secretKeyRef:
              name: swissproxy
              key: proxy_url
        - name: https_proxy
          valueFrom:
            secretKeyRef:
              name: swissproxy
              key: proxy_url
        - name: PIPELINE_SA_TOKEN
          valueFrom:
            secretKeyRef:
              name: pipeline-token-5wqng
              key: token
        name: github-runner
        image: ghcr.io/axa-ch-cloud/trap-github-runner:latest
        resources:
          {{- toYaml .Values.resources.container | nindent 10 }}
        volumeMounts:
          - name: volume-cacert
            mountPath: /cacert
        volumeMount:
            - name: volume-age-key
              mountPath: /home/github/config
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      volumes:
      - name: volume-cacert
        secret:
          secretName: cacerts-red
          defaultMode: 420
      - name: volume-age-key
        secret:
          secretName: age-secret-key
          defaultMode: 420
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1001860000
      imagePullSecrets:
        - name: docker-github-trap
      terminationGracePeriodSeconds: 40
  test: false
  triggers: []
