kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: github-actions-runner
  labels:
    build: github-actions-runner
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: >-
    image-registry.openshift-image-registry.svc:5000/trap-dev-axa-ch/github-actions-runner
